DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE ZEPTO (
    ID SERIAL PRIMARY KEY,
    CATEGORY VARCHAR(120),
    NAME VARCHAR(150) NOT NULL,
    MRP NUMERIC(8,2),
    DISCOUNTPERCENT NUMERIC(5,2),
    AVAILABLEQUANTITY INTEGER,
    DISCOUNTEDSELLINGPRICE NUMERIC(8,2),
    WEIGHTINGMS INTEGER,
    OUTOFSTOCK BOOLEAN,
    QUANTITY INTEGER
);


-- DATA EXPLORATION

SELECT COUNT(*) FROM ZEPTO;


-- SAMPLE DATA

SELECT * FROM ZEPTO LIMIT 10;


-- NULL VALUES

SELECT * FROM ZEPTO
WHERE NAME IS NULL
OR CATEGORY IS NULL
OR MRP IS NULL
OR DISCOUNTPERCENT IS NULL
OR DISCOUNTEDSELLINGPRICE IS NULL
OR WEIGHTINGMS IS NULL
OR AVAILABLEQUANTITY IS NULL
OR OUTOFSTOCK IS NULL
OR QUANTITY IS NULL;


-- DIFFERENT PRODUCT CATEGORIES

SELECT DISTINCT CATEGORY
FROM ZEPTO
ORDER BY CATEGORY;


-- INSTOCK AND OUTSTOCK PRODUCTS

SELECT OUTOFSTOCK, COUNT(ID)
FROM ZEPTO
GROUP BY OUTOFSTOCK;


-- PRODUCT NAMES PRESENT MULTIPLE TIMES

SELECT NAME, COUNT(ID) AS "NUMBER OF PRODUCT"
FROM ZEPTO
GROUP BY NAME
HAVING COUNT(ID) > 1
ORDER BY COUNT(ID) DESC;


-- DATA CLEANING

-- PRODUCT WITH PRICE MIGHT BE ZERO

SELECT *
FROM ZEPTO
WHERE MRP = 0
OR DISCOUNTEDSELLINGPRICE = 0;


-- WE HAVE ONE ROW WITH PRICE = 0

-- DELETING IT

DELETE FROM ZEPTO
WHERE MRP = 0;


-- SELLING PRICE AND DISCOUNTED PRICES ARE CURRENTLY IN PAISE

-- CONVERTING FROM PAISE TO RUPEES

UPDATE ZEPTO
SET MRP = MRP / 100.0,
    DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE / 100.0;


SELECT MRP, DISCOUNTEDSELLINGPRICE
FROM ZEPTO;


-- BUSINESS INSIGHTS


-- TOP 10 BEST VALUE-PRODUCTS BASED ON DISCOUNT PERCENTAGE

SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;

-- THESE PRODUCTS ARE BEING SOLD WITH ROUGHLY HALF OF THE PRICE
-- IT HELPS CUSTOMERS BECAUSE OF THE LOWER PURCHASE COST
-- IN BUSINESS VIEW IT CAN ATTRACT CUSTOMERS WHO WON'T BUY AT FULL PRICES
-- CUSTOMERS MIGHT SEE 50% DISCOUNT AND MAKE THEIR MIND TO TRY THE PLATFORM
-- IT IMPROVES PLATFORM ENGAGEMENT
-- THESE MIGHT REDUCE PROFIT MARGIN


-- HOW MUCH CUSTOMERS SAVE MONEY ON EACH PRODUCT

SELECT
    NAME,
    MRP,
    DISCOUNTEDSELLINGPRICE,
    MRP - DISCOUNTEDSELLINGPRICE AS DISCOUNT_AMOUNT,
    DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNT_AMOUNT DESC
LIMIT 10;


-- HIGHER DISCOUNT AMOUNTS CAN MAKE PRODUCTS MORE ATTRACTIVE TO CUSTOMERS
-- AND ENCOURAGE MORE PURCHASES.


-- PRODUCTS WITH HIGH MRP BUT OUT OF STOCK

SELECT DISTINCT NAME, MRP
FROM ZEPTO
WHERE OUTOFSTOCK = TRUE
AND MRP > 300
ORDER BY MRP DESC;

-- THESE ARE HIGH PRICED PRODUCTS
-- COMPANY MIGHT NEED TO RESTOCK THEM AS SOON AS POSSIBLE
-- IF CUSTOMERS ARE BUYING THEM FREQUENTLY


-- ESTIMATED REVENUE FOR EACH CATEGORY

SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- THIS SHOWS WHICH CATEGORY CAN GENERATE THE MOST REVENUE
-- BASED ON THE CURRENT AVAILABLE INVENTORY


-- ALL PRODUCTS WHERE MRP IS GREATER THAN ₹500
-- AND DISCOUNT IS LESS THAN 10%

SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP > 500
AND DISCOUNTPERCENT < 10
ORDER BY MRP DESC, DISCOUNTPERCENT DESC;

-- THESE ARE DAILY-USE PRODUCTS WITH HIGH MRP BUT VERY LOW DISCOUNTS
-- THIS MAY INDICATE THAT CUSTOMERS REGULARLY NEED THEM
-- AND THERE MAY BE LESS NEED FOR HEAVY DISCOUNTS


-- TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE

SELECT CATEGORY,
ROUND(AVG(DISCOUNTPERCENT), 2) AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;

-- THIS IS VERY USEFUL FOR MARKETING TEAMS
-- TO SEE WHERE THE PRICE CUT IS HAPPENING MOST


-- THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G
-- AND SORT BY BEST VALUE

SELECT DISTINCT NAME, WEIGHTINGMS, DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS, 2) AS PRICE_PER_GRAM
FROM ZEPTO
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GRAM ASC;

-- THIS HELPS CUSTOMERS TO COMPARE VALUE FOR MONEY FOR PRODUCTS
-- AND EVEN FOR INTERNAL PRICING STRATEGIES
-- FOR EXAMPLE, IF WE HAVE PROTEIN PRODUCTS,
-- WE COULD USE A SIMILAR APPROACH TO SHOW HOW MUCH CUSTOMERS
-- PAY FOR EACH GRAM OF PROTEIN.


-- GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW, MEDIUM, BULK

SELECT DISTINCT NAME, WEIGHTINGMS,
CASE
    WHEN WEIGHTINGMS < 1000 THEN 'LOW'
    WHEN WEIGHTINGMS < 5000 THEN 'MEDIUM'
    ELSE 'BULK'
END AS WEIGHT_CATEGORY
FROM ZEPTO;


-- THIS HELPS US UNDERSTAND WHETHER PRODUCTS ARE MAINLY
-- SOLD IN SMALL, MEDIUM OR BULK PACK SIZES


-- THE TOTAL INVENTORY WEIGHT PER CATEGORY

SELECT CATEGORY,
SUM(WEIGHTINGMS * AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT DESC;

-- THIS HELPS IN INVENTORY MANAGEMENT AND WAREHOUSE PLANNING


-- =========================================================
-- ADVANCED SQL
-- =========================================================


-- PRODUCTS WITH DISCOUNT HIGHER THAN THE AVERAGE DISCOUNT

SELECT
    NAME,
    CATEGORY,
    DISCOUNTPERCENT
FROM ZEPTO
WHERE DISCOUNTPERCENT > (
    SELECT AVG(DISCOUNTPERCENT)
    FROM ZEPTO
)
ORDER BY DISCOUNTPERCENT DESC;

-- THIS HELPS US FIND PRODUCTS WHERE THE DISCOUNT
-- IS HIGHER THAN THE OVERALL AVERAGE DISCOUNT
-- THESE PRODUCTS ARE GETTING MORE DISCOUNT THAN MOST PRODUCTS


-- CATEGORY WISE AVERAGE DISCOUNT

WITH CATEGORY_DISCOUNT AS (
    SELECT
        CATEGORY,
        ROUND(AVG(DISCOUNTPERCENT), 2) AS AVG_DISCOUNT
    FROM ZEPTO
    GROUP BY CATEGORY
)
SELECT
    CATEGORY,
    AVG_DISCOUNT
FROM CATEGORY_DISCOUNT
ORDER BY AVG_DISCOUNT DESC;

-- THIS HELPS US UNDERSTAND WHICH CATEGORIES
-- ARE GETTING MORE DISCOUNTS ON AVERAGE
-- THIS IS USEFUL FOR MARKETING TEAMS
-- TO SEE WHERE THE PRICE CUT IS HAPPENING MOST


-- TOP 3 PRODUCTS WITH HIGHEST DISCOUNT
-- FROM EACH CATEGORY

WITH RANKED_PRODUCTS AS (
    SELECT
        CATEGORY,
        NAME,
        DISCOUNTPERCENT,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY DISCOUNTPERCENT DESC
        ) AS PRODUCT_RANK
    FROM ZEPTO
)
SELECT
    CATEGORY,
    NAME,
    DISCOUNTPERCENT,
    PRODUCT_RANK
FROM RANKED_PRODUCTS
WHERE PRODUCT_RANK <= 3
ORDER BY CATEGORY, PRODUCT_RANK;

-- THIS HELPS US FIND THE PRODUCTS WITH THE HIGHEST DISCOUNTS
-- INSIDE EACH CATEGORY
-- THIS CAN HELP US UNDERSTAND WHICH PRODUCTS
-- ARE BEING PROMOTED MORE IN EACH CATEGORY


-- RANK PRODUCTS BASED ON DISCOUNT
-- WITHIN EACH CATEGORY

SELECT
    CATEGORY,
    NAME,
    DISCOUNTPERCENT,
    RANK() OVER (
        PARTITION BY CATEGORY
        ORDER BY DISCOUNTPERCENT DESC
    ) AS DISCOUNT_RANK
FROM ZEPTO
ORDER BY CATEGORY, DISCOUNT_RANK;

-- THIS HELPS US COMPARE PRODUCTS WITHIN THE SAME CATEGORY
-- AND FIND WHICH PRODUCTS HAVE THE HIGHEST DISCOUNT
-- COMPARED TO OTHER PRODUCTS IN THE SAME CATEGORY


-- TOP 3 PRODUCTS BASED ON DISCOUNT AMOUNT
-- WITHIN EACH CATEGORY

WITH DISCOUNT_AMOUNT_DATA AS (
    SELECT
        CATEGORY,
        NAME,
        MRP,
        DISCOUNTEDSELLINGPRICE,
        MRP - DISCOUNTEDSELLINGPRICE AS DISCOUNT_AMOUNT
    FROM ZEPTO
),
RANKED_DISCOUNTS AS (
    SELECT
        CATEGORY,
        NAME,
        MRP,
        DISCOUNTEDSELLINGPRICE,
        DISCOUNT_AMOUNT,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY DISCOUNT_AMOUNT DESC
        ) AS DISCOUNT_RANK
    FROM DISCOUNT_AMOUNT_DATA
)
SELECT
    CATEGORY,
    NAME,
    MRP,
    DISCOUNTEDSELLINGPRICE,
    DISCOUNT_AMOUNT,
    DISCOUNT_RANK
FROM RANKED_DISCOUNTS
WHERE DISCOUNT_RANK <= 3
ORDER BY CATEGORY, DISCOUNT_RANK;

-- THIS HELPS US FIND WHICH PRODUCTS GIVE CUSTOMERS
-- THE HIGHEST DISCOUNT AMOUNT WITHIN EACH CATEGORY
-- THIS CAN HELP CUSTOMERS FIND PRODUCTS WHERE THEY SAVE MORE MONEY


-- TOP 10 PRODUCTS WITH HIGHEST CURRENT INVENTORY VALUE

SELECT
    NAME,
    CATEGORY,
    AVAILABLEQUANTITY,
    DISCOUNTEDSELLINGPRICE,
    DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY AS INVENTORY_VALUE
FROM ZEPTO
ORDER BY INVENTORY_VALUE DESC
LIMIT 10;

-- THIS SHOWS WHICH PRODUCTS HAVE THE HIGHEST CURRENT
-- INVENTORY VALUE BASED ON AVAILABLE STOCK AND SELLING PRICE
-- THIS CAN HELP THE BUSINESS UNDERSTAND WHICH PRODUCTS
-- HAVE MORE MONEY CURRENTLY TIED UP IN INVENTORY


-- PRODUCTS WITH HIGH DISCOUNT AND LOW AVAILABLE STOCK

SELECT
    NAME,
    CATEGORY,
    DISCOUNTPERCENT,
    AVAILABLEQUANTITY,
    OUTOFSTOCK
FROM ZEPTO
WHERE DISCOUNTPERCENT >= 30
AND AVAILABLEQUANTITY <= 3
ORDER BY DISCOUNTPERCENT DESC;

-- THESE PRODUCTS HAVE HIGH DISCOUNTS BUT LOW AVAILABLE STOCK
-- THIS CAN HELP THE BUSINESS IDENTIFY PRODUCTS
-- THAT MAY NEED BETTER INVENTORY PLANNING
-- ESPECIALLY WHEN PRODUCTS ARE BEING PROMOTED